### ISSUE TITLE
Cannot find module 'mongoose'

### ISSUE THREAD

**Issue by alexprice91** [GetStream/stream-node-orm#21]
I am trying to run this according this docs:
https://getstream.io/docs/js/#enrichment

I am getting this error:
```
Error: Cannot find module 'mongoose'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/alexprice/code/private/opt-in/node_modules/getstream-node/src/backends/mongoose.js:4:16)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/alexprice/code/private/opt-in/node_modules/getstream-node/src/index.js:5:16)
```

**Comment by alexprice91** [comment]
I have mongoose installed.

**Comment by alexprice91** [comment]
Closing. It was installed on the wrong directory.
